services:
  - type: web
    name: chinitodl
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: HEADLESS
        value: true
